version: "3.7"
services:
  postgres:
    container_name: 'user_db'
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  test_db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  user:
    container_name: 'user'
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn user.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    depends_on:
      - "postgres"
      - "test_db"
    ports:
      - "8001:8001"
    volumes:
      - ./user:/app/user
      - ./alembic:/app/alembic
      - ./tests:/app/tests

volumes:
  db-data:
  test_db_data:
