"""add cost_per_lesson_filed_&_remove_cost_filed_for_student

Revision ID: 46797f82aef1
Revises: cf966c512342
Create Date: 2024-05-27 17:11:30.220046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46797f82aef1'
down_revision: Union[str, None] = 'cf966c512342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'cost')
    op.add_column('tutor', sa.Column('cost_per_lesson', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'cost_per_lesson')
    op.add_column('student', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
